/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Record = IDL.Record({
  'id' : IDL.Nat,
  'mcf' : IDL.Text,
  'remark' : IDL.Text,
  'customerName' : IDL.Text,
  'netAmount' : IDL.Text,
  'finance' : IDL.Text,
  'loanAmount' : IDL.Text,
  'createdAt' : IDL.Int,
  'grossAmount' : IDL.Text,
  'bankAmountReceivedDate' : IDL.Opt(IDL.Text),
  'brokerageAmountReceivedDate' : IDL.Opt(IDL.Text),
  'product' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(Record)], ['query']),
  'getRecord' : IDL.Func([IDL.Nat], [Record], ['query']),
  'updateRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Record = IDL.Record({
    'id' : IDL.Nat,
    'mcf' : IDL.Text,
    'remark' : IDL.Text,
    'customerName' : IDL.Text,
    'netAmount' : IDL.Text,
    'finance' : IDL.Text,
    'loanAmount' : IDL.Text,
    'createdAt' : IDL.Int,
    'grossAmount' : IDL.Text,
    'bankAmountReceivedDate' : IDL.Opt(IDL.Text),
    'brokerageAmountReceivedDate' : IDL.Opt(IDL.Text),
    'product' : IDL.Text,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(Record)], ['query']),
    'getRecord' : IDL.Func([IDL.Nat], [Record], ['query']),
    'updateRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };